; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare-esp32-s3-lcd-316]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = waveshare-esp32-s3-lcd-316
framework = arduino
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags = 
	-DLV_CONF_PATH='"${PROJECT_DIR}/include/lv_conf.h"'
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = lvgl/lvgl@^9.5.0
